spring.application.name=auth-service
spring.config.import=optional:file:.env[.properties],optional:file:auth-service/.env[.properties]
# Conexion a Supabase
spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

# JWT Configuration
jwt.secret=${JWT_SECRET:8a9b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b}
jwt.expiration-time=${JWT_EXPIRATION_TIME}
jwt.refresh-expiration-time=${JWT_REFRESH_EXPIRATION_TIME}

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

# Schema por defecto
spring.jpa.properties.hibernate.default_schema=seguridad_ms

#Configuracion del puerto
server.port=8085

#Configuracion Autenticacion
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USER}
spring.mail.password=${EMAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Disable SpringDoc actuator integration unless actuator is enabled/added as a dependency
springdoc.show-actuator=false
springdoc.api-docs.enabled=true

server.forward-headers-strategy=framework