spring.application.name=auth-service
spring.config.import=optional:file:.env[.properties]
# Conexion a Supabase
spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

# JWT Configuration
jwt.secret=${JWT_SECRET:8a9b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b}
jwt.expiration-time=${JWT_EXPIRATION_TIME:900000}

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

# Schema por defecto
spring.jpa.properties.hibernate.default_schema=seguridad_ms


server.port=8085